2018-05-25 21:53:46,839 ERROR: Exception on /profile/tntwizardx [GET] [in c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Bob\Desktop\Programming\SRWeb\app\routes.py", line 72, in profile
    games = Game.query.filter_by(author=current_user.username)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1632, in filter_by
    for key, value in kwargs.items()]
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1632, in <listcomp>
    for key, value in kwargs.items()]
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 344, in __eq__
    return self.operate(eq, other)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 180, in operate
    return op(self.comparator, *other, **kwargs)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1039, in __eq__
    other, adapt_source=self.adapter))
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\relationships.py", line 1372, in _optimized_compare
    state = attributes.instance_state(state)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2018-05-25 21:57:03,571 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-25 21:57:23,046 ERROR: Exception on /profile/tntwizardx [GET] [in c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Bob\Desktop\Programming\SRWeb\app\routes.py", line 75, in profile
    " on " + g.map)
TypeError: Can't convert 'int' object to str implicitly
2018-05-25 21:58:45,475 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-25 21:59:26,422 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-25 21:59:55,384 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-25 22:09:28,962 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-25 22:27:53,838 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-26 00:39:43,243 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-26 00:43:30,497 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
2018-05-26 00:47:03,640 ERROR: Exception on /submit/ [POST] [in c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Bob\Desktop\Programming\SRWeb\app\routes.py", line 56, in submit
    author=User.query.filter_by(username=current_user.username))
  File "<string>", line 4, in __init__
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 700, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 229, in __set__
    instance_dict(instance), value, None)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 813, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 833, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "c:\users\bob\desktop\programming\srweb\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 1181, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'BaseQuery' object has no attribute '_sa_instance_state'
2018-05-26 00:49:28,841 INFO: SRWeb startup [in C:\Users\Bob\Desktop\Programming\SRWeb\app\__init__.py:45]
